PLUGINS = {   
    "0": "Directory browsing",
    "1": "Potential File Path Manipulation",
    "2": "Private IP disclosure",
    "3": "Session ID in URL rewrite",
    "6": "Directory/Path traversal",
    "7": "Remote File Inclusion",
    '10001': 'Secure page browser cache',
    '10010': 'Cookie set without HttpOnly flag',
    '10011': 'Cookie set without secure flag',
    '10012': 'Password Autocomplete in browser',
    '10013': 'Weak HTTP authentication over an unsecured connection',
    '10014': 'Cross Site Request Forgery',
    '10015': 'Incomplete or no cache-control and pragma HTTPHeader set',
    '10016': "IE8's XSS protection filter not disabled",
    '10017': "Cross-domain JavaScript source file inclusion",
    '10018': "Untrusted domains in JavaScript source code",
    '10019': "Content-Type header missing",
    '10020': "X-Frame-Options header not set",
    '10021': "X-Content-Type-Options header missing",
    '10022': "Information disclosure - database error messages",
    '10023': "Information disclosure - debug error messages",
    '10024': "Information disclosure - sensitive informations in URL",
    '10025': "Information disclosure - sensitive informations on HTTP Referrer header",
    '10026': "HTTP Parameter Override",
    '10027': "Information disclosure - suspicious comments",
    '10028': "Open redirect",
    '10029': "Cookie poisoning",
    '10030': "User controllable charset",
    '10031': "User controllable HTML element attribute (potential XSS)",
    '20010': "URL Redirector Abuse",
    '30000': "External redirect",
    '40000': "Cross site scripting",
    '40001': "Cross site scripting in SCRIPT section",
    '40002': "Cross site scripting without brackets",
    '40012': "Cross site scripting (Reflected)",
    '40003': "CRLF injection",
    '40004': "SQL Injection Fingerprinting",
    '40005': "SQL Injection",
    '40006': "MS SQL Injection Enumeration",
    '40007': "Oracle SQL Injection Enumeration",
    '40008': "Parameter tampering",
    '40009': "Server side include",
    '40010': "Cross site scripting in TAG",
    '40011': "Cross Site Scripting in TAG Attribute",
    '50000': "Active Scan scripts",
    '50001': "Passive Scan scripts"
}



WASC_MAP = {
    '1': 'http://projects.webappsec.org/Insufficient-Authentication',
    '2': 'http://projects.webappsec.org/Insufficient-Authorization',
    '3': 'http://projects.webappsec.org/Integer-Overflows',
    '4': 'http://projects.webappsec.org/Insufficient-Transport-Layer-Protection',
    '5': 'http://projects.webappsec.org/Remote-File-Inclusion',
    '6': 'http://projects.webappsec.org/Format-String',
    '7': 'http://projects.webappsec.org/Buffer-Overflow',
    '8': 'http://projects.webappsec.org/Cross-Site-Scripting',
    '9': 'http://projects.webappsec.org/Cross-Site-Request-Forgery',
    '10': 'http://projects.webappsec.org/Denial-of-Service',
    '11': 'http://projects.webappsec.org/Brute-Force',
    '12': 'http://projects.webappsec.org/Content-Spoofing',
    '13': 'http://projects.webappsec.org/Information-Leakage',
    '14': 'http://projects.webappsec.org/Server-Misconfiguration',
    '15': 'http://projects.webappsec.org/Application-Misconfiguration',
    '16': 'http://projects.webappsec.org/Directory-Indexing',
    '17': 'http://projects.webappsec.org/Improper-Filesystem-Permissions',
    '18': 'http://projects.webappsec.org/Credential-and-Session-Prediction',
    '19': 'http://projects.webappsec.org/SQL-Injection',
    '20': 'http://projects.webappsec.org/Improper-Input-Handling',
    '21': 'http://projects.webappsec.org/Insufficient+Anti-automation',
    '22': 'http://projects.webappsec.org/Improper-Output-Handling',
    '23': 'http://projects.webappsec.org/XML-Injection',
    '24': 'http://projects.webappsec.org/HTTP-Request-Splitting',
    '25': 'http://projects.webappsec.org/HTTP-Response-Splitting',
    '26': 'http://projects.webappsec.org/HTTP-Request-Smuggling',
    '27': 'http://projects.webappsec.org/HTTP-Response-Smuggling',
    '28': 'http://projects.webappsec.org/Null-Byte-Injection',
    '29': 'http://projects.webappsec.org/LDAP-Injection',
    '30': 'http://projects.webappsec.org/Mail-Command-Injection',
    '31': 'http://projects.webappsec.org/OS-Commanding',
    '32': 'http://projects.webappsec.org/Routing-Detour',
    '33': 'http://projects.webappsec.org/Path-Traversal',
    '34': 'http://projects.webappsec.org/Predictable-Resource-Location',
    '35': 'http://projects.webappsec.org/SOAP-Array-Abuse',
    '36': 'http://projects.webappsec.org/SSI-Injection',
    '37': 'http://projects.webappsec.org/Session-Fixation',
    '38': 'http://projects.webappsec.org/URL-Redirector-Abuse',
    '39': 'http://projects.webappsec.org/XPath-Injection',
    '40': 'http://projects.webappsec.org/Insufficient-Process-Validation',
    '41': 'http://projects.webappsec.org/XML-Attribute-Blowup',
    '42': 'http://projects.webappsec.org/Abuse-of-Functionality',
    '43': 'http://projects.webappsec.org/XML-External-Entities',
    '44': 'http://projects.webappsec.org/XML-Entity-Expansion',
    '45': 'http://projects.webappsec.org/Fingerprinting',
    '46': 'http://projects.webappsec.org/XQuery-Injection',
    '47': 'http://projects.webappsec.org/Insufficient-Session-Expiration',
    '48': 'http://projects.webappsec.org/Insecure-Indexing',
    '49': 'http://projects.webappsec.org/Insufficient-Password-Recovery',
    '50': 'http://projects.webappsec.org/Insufficient-Data-Protection'
}
